### ISSUE TITLE
Question about Cloud Deployment

### ISSUE THREAD

**Issue by Strepto** [Unity-Technologies/UnityRenderStreaming#228]
Hi,

I am looking at the FAQ, where it says that "Unity is not supported for rendering server". What does this mean, and where can I get more information about this?

Is there any preventing me from deploying this to a cloud service like Azure or Google Cloud Platform?

--
```
## Is it available to deploy Unity to cloud service like GCP as a rendering server?

Unity is not supported using for rendering server.
```
Copied from: https://github.com/Unity-Technologies/UnityRenderStreaming/blob/release/1.1.3/Packages/com.unity.renderstreaming/Documentation~/en/faq.md#is-it-available-to-deploy-unity-to-cloud-service-like-gcp-as-a-rendering-server

**Comment by Nemo-G** [comment]
Hi @Strepto , at very early stage I've participated a little in the integration of RenderStreaming. I would share some of my thoughts on this.

Technically you can deploy a dedicated server in a cloud service vendor like GCP/AWS running Unity. But there are few things you should take into consideration:

1. As WebRTC has been used, to support a stable service, you'd better implement your own signal server and also setup your own stun/turn server. Otherwise your client can easily be kicked out.

2. RenderStreaming is a CPU/GPU heavy project. And it is costly to use such machine in a public cloud service provider. And in one physical machine, you can just run a few streaming project. Unity would not provide such server according to FAQ.

My colleagues from RenderStreaming team may answer you better. Just hope it helps!

**Comment by Strepto** [comment]
Thank you for your insights.

If I understand you correctly, it is OK to self-host my Unity Render Streaming solution in AWS. Unity will not support me in setting this up, but will not stop me from doing so either?

**Comment by sindharta** [comment]
Unity will definitely not stop you from hosting your solution in AWS.
We will appreciate it if you let us know how it goes.

**Comment by Strepto** [comment]
Thank you! Marking this as resolved.
