### ISSUE TITLE
Android Chrome connection issue

### ISSUE THREAD

**Issue by mehdikhadir** [Unity-Technologies/UnityRenderStreaming#252]
Hello,
I have an issue when trying to connect as a receiver on Chrome/Android. The connection doesn't seem to get established. That's what the Unity console tells me on my Windows machine:

Network Error: Unity.WebRTC.RTCError
UnityEngine.Debug:LogError(Object)
Unity.RenderStreaming.d__20:MoveNext() (at Assets/Scripts/RenderStreaming.cs:183)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

![image](https://user-images.githubusercontent.com/47895138/77890594-068c8f00-7270-11ea-90d9-57dba1a956f5.png)

Nothing specific appears in the webserver.exe console apart from the IP addresses of the broadcasting device.

The connection works fine with Chrome/MacOS as a receiver. I'm using the preview release version 1.2.3
Do you have any idea where the issue might come from?
Thanks in advance.

**Comment by karasusan** [comment]
I believe the issue caused by firewall. You can see the post on Unity Forum which is same the issue.
https://forum.unity.com/threads/unity-render-streaming-introduction-faq.742481/page-5#post-5642947

**Comment by soraryu** [comment]
I have the same issue, even with Firewall turned off.
Unity 2019.3.12f1, RenderStreaming 2.0.1

**Comment by karasusan** [comment]
OK, I will investigate the issue.
First, we need to clarify which one by a network issue or a browser issue.

@soraryu 
Could you tell me the Android version and Chrome version?

**Comment by soraryu** [comment]
Sure!

Android 10 QkQ1.190825.002
Chrome 81.0.4044.138

This is a pretty high-end device (Xiaomi Mi 9). Let me know if there's anything else I can get you to debug that.

**Comment by soraryu** [comment]
I have an idea that it has something to do with machine ethernet adapter configuration, but not sure. There's some open bugs about that with Unity (esp. laptops that have both ethernet and wifi adapters, with ethernet unused but active since otherwise Hub does not work at all).
So maybe sending / receiving has issues if there are multiple adapters present but not all of them connected to the internet? You should be able to verify this from a laptop with ethernet + wifi adapter.

**Comment by karasusan** [comment]
I don't have the laptop you said so it is difficult to reproduce the problem...
I have a question. Do you reproduce the issue if you try with the other PC?

**Comment by samghafari** [comment]
I had the same error, I managed to connect by removing the chrome cache.

**Comment by soraryu** [comment]
@karasusan I was able to localize the issue even further; no matter where the stream originates from (local network, over internet, ...) I'm able to access it from desktop but not from any mobile (Android / iOS). It works from mobile when I use 4G network instead of local Wifi.

Local Wifi is provided by a Google Wifi router, with Upnp etc. all active and enabled. 
Official WebRTC samples all work fine, not sure what else I could configure to make that work - my assumption is that _something_ about the sender prevents receiving the stream under this condition.

**Comment by karasusan** [comment]
@sorayu Thanks for sharing. It seems difficult to solve it at once.

**Comment by soraryu** [comment]
How can I help? What can I test? I can give you remote access for debugging if needed; Google WiFi isn't exactly a rare setup, and as said, it works great with other WebRTC applications.

**Comment by christianstamati** [comment]
Hi @hybridherbst I have Xiaomi Mi 9T and I have the same problem... But It's very strange because sometimes does work.. Did you find solution? I also tried to use https and I installed crt and the key files but when I connect to https but I have this problem:
```
Access to 192.168.1.131 was denied
You don't have authorization to view this page.
HTTP ERROR 403
```

**Comment by christianstamati** [comment]
I tried deleting the cache, it works! Thanks! @samghafari

**Comment by jimengying** [comment]
I have the same problem. I tried deleting the cache,but it didn't work.Has the problem been solved now?

**Comment by samghafari** [comment]
> I have the same problem. I tried deleting the cache,but it didn't work.Has the problem been solved now?

what seems to be the issue? are you setting your stun server ? I managed to use a local stun server by stunman.

**Comment by kannan-xiao4** [comment]
I was able to reproduce this issue when I turned on the Firewall on Windows running the Editor.
However, by turning off the Firewall, I was able to receive the video on Android/Chrome.

Below is the error when the Firewall is on
![image](https://user-images.githubusercontent.com/26959415/91514902-e9ddab80-e922-11ea-9a7a-feaa20768d6d.png)

Are you currently getting an error log on the same line as my image (Renderstreaming.cs:L190)?

Android device is Galaxy S7
- Chrome 84.0.4147.125
- Android 8.0.0; SM-G930F Build/R16NW

**Comment by JinghaoZhao** [comment]
I met the same issue on Android phones. Sometimes (around 1/3) I can receive the stream but for other times the Unity.Webrtc.RTCError appears. All the firewalls of my Windows PC are closed thus the problem may not be caused by the firewall. 

I tested it on Google Pixel, Xiaomi MI6, Samsung Galaxy s9 and the behaviors are similar to above. 
All the phones are Android 9 and the chrome version of my test phones are the latest version (86.0.4240.99)

**Comment by karasusan** [comment]
@JinghaoZhao Hi, which version of the package are you using?

**Comment by kannan-xiao4** [comment]
maybe, I reproduce it.
but, this only happened when I first started Chrome. I reload page, this fix.
The reason for the problem was that H264Codec was not included in the SDP.
(current unity.webrtc  `version 2.1` only supported h264 codec for encoder, so receiver need to support h264 decoder)

We can check h264 codec support on below.
https://codepen.io/manjeshbhargav/pen/yLYMvZE

Please check it!

**Comment by JinghaoZhao** [comment]
> @JinghaoZhao Hi, which version of the package are you using?

I use the latest 2.1.1-preview

**Comment by kannan-xiao4** [comment]
https://github.com/Unity-Technologies/UnityRenderStreaming/issues/252#issuecomment-716264620

Current Android Chrome fixed this problem. (version 88.0.4324.152)
Please try to use latest chrome.

@mehdikhadir @JinghaoZhao
